version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.4.0
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "package-lock.json" }}
            # Perform a Partial Cache Restore (https://circleci.com/docs/2.0/caching/#restoring-cache)
            - v1-dependencies-
      - run:
          name: Install OpenJDK 14
          command: |
            sudo rm /var/lib/apt/lists/lock
            sudo rm /var/cache/apt/archives/lock
            sudo rm /var/lib/dpkg/lock
            sudo apt install openjdk-14-jdk
            echo 'export PATH="/usr/lib/jvm/java-14-openjdk-amd64/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Print Versions
          command: java -version
      - run:
          name: Give Executable Power
          command: 'chmod +x gradlew'
      - run:
          name: Verify with Prod Profile
          command: './gradlew bootJar -Pprod -x test jibDockerBuild --no-daemon'
      - gcp-cli/initialize
      - run:
          name: Tag docker image
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV
            echo 'export GOOGLE_PROJECT_ID=$GOOGLE_PROJECT_ID' >> $BASH_ENV
            echo 'export TAG=${CIRCLE_SHA1}' >> $BASH_ENV
            echo 'export IMAGE_NAME=$CIRCLE_PROJECT_REPONAME' >> $BASH_ENV && source $BASH_ENV
            docker build . -t botwebhook
            docker tag botwebhook gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME
            docker tag botwebhook gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME:$TAG
            sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update
            gcloud auth configure-docker
            docker push gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME:$TAG
      - run:
          name: Deploy docker image to GCP
          command:
            gcloud run deploy schedulify --image=gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME:$TAG --allow-unauthenticated --timeout=3600 --memory=512Mi --platform=managed --region=${GOOGLE_COMPUTE_REGION} --project=${GOOGLE_PROJECT_ID} --min-instances=1 --max-instances=1 --port=8080  --set-secrets=SCHEDULIFY_TELEGRAM_BOT_NAME=SCHEDULIFY_TEST_TELEGRAM_BOT_NAME:latest,SCHEDULIFY_TELEGRAM_BOT_TOKEN=SCHEDULIFY_TEST_TELEGRAM_BOT_TOKEN:latest 
